package main

import (
	"fmt"
	"os"
	"strings"
)

// profileKnobs returns the routing-knob env vars / YAML keys + values
// that the named profile bundles. Keeping the mapping in one place
// means the .env and config.yaml writers never drift apart.
func profileKnobs(profile string) map[string]string {
	switch profile {
	case profileLocalFirst:
		// Lower confidence threshold so more traffic stays local.
		return map[string]string{
			"NEXUS_SLM_CONFIDENCE_THRESHOLD": "0.2",
		}
	case profileFrontierDefault:
		// Higher threshold pushes ambiguous traffic to frontier.
		return map[string]string{
			"NEXUS_SLM_CONFIDENCE_THRESHOLD": "0.6",
		}
	case profileFusionBalanced:
		// Defaults — fusion enabled, agreement threshold at default.
		return map[string]string{
			"NEXUS_FUSION_AGREEMENT_THRESHOLD": "0.85",
		}
	default:
		return nil
	}
}

// profileYAMLKeys maps env-var names to their snake_case YAML keys for
// the subset of knobs the profiles touch.
var profileYAMLKeys = map[string]string{
	"NEXUS_SLM_CONFIDENCE_THRESHOLD":   "slm_confidence_threshold",
	"NEXUS_FUSION_AGREEMENT_THRESHOLD": "fusion_agreement_threshold",
}

// writeEnvConfig renders the answers as a .env file. The format is
// `KEY=value`, one per line, with the profile knobs appended so the
// generated file captures the preset choice.
func writeEnvConfig(path string, ans initAnswers) error {
	var b strings.Builder
	b.WriteString("# Generated by `nexus init`.\n")
	b.WriteString("# Environment variables for the Nexus Proxy.\n\n")

	b.WriteString("# --- Local Ollama ---------------------------------------------------------\n")
	fmt.Fprintf(&b, "NEXUS_OLLAMA_URL=%s\n", ans.OllamaURL)
	fmt.Fprintf(&b, "NEXUS_ROUTER_MODEL=%s\n", ans.RouterModel)
	fmt.Fprintf(&b, "NEXUS_LOCAL_MODEL=%s\n", ans.LocalModel)
	fmt.Fprintf(&b, "NEXUS_EMBEDDING_MODEL=%s\n", ans.EmbeddingModel)
	b.WriteString("\n")

	b.WriteString("# --- Frontier API ---------------------------------------------------------\n")
	fmt.Fprintf(&b, "NEXUS_FRONTIER_URL=%s\n", ans.FrontierURL)
	fmt.Fprintf(&b, "NEXUS_FRONTIER_MODEL=%s\n", ans.FrontierModel)
	fmt.Fprintf(&b, "NEXUS_FRONTIER_API_KEY=%s\n", ans.FrontierKey)
	b.WriteString("\n")

	b.WriteString("# --- Inbound auth ---------------------------------------------------------\n")
	fmt.Fprintf(&b, "NEXUS_PROXY_API_KEY=%s\n", ans.ProxyAPIKey)
	b.WriteString("\n")

	b.WriteString("# --- Routing profile ------------------------------------------------------\n")
	fmt.Fprintf(&b, "# profile: %s\n", ans.Profile)
	for k, v := range profileKnobs(ans.Profile) {
		fmt.Fprintf(&b, "%s=%s\n", k, v)
	}
	b.WriteString("\n")

	return os.WriteFile(path, []byte(b.String()), 0o600)
}

// writeYAMLConfig renders the answers as a config.yaml file using the
// snake_case keys the YAML parser expects. Only the keys the wizard
// touches are written; everything else falls back to LoadYAML defaults.
func writeYAMLConfig(path string, ans initAnswers) error {
	var b strings.Builder
	b.WriteString("# Generated by `nexus init`.\n")
	b.WriteString("# YAML configuration for the Nexus Proxy.\n\n")

	b.WriteString("# --- Local Ollama ---------------------------------------------------------\n")
	fmt.Fprintf(&b, "ollama_url: %q\n", ans.OllamaURL)
	fmt.Fprintf(&b, "router_model: %q\n", ans.RouterModel)
	fmt.Fprintf(&b, "local_model: %q\n", ans.LocalModel)
	fmt.Fprintf(&b, "embedding_model: %q\n", ans.EmbeddingModel)
	b.WriteString("\n")

	b.WriteString("# --- Frontier API ---------------------------------------------------------\n")
	fmt.Fprintf(&b, "frontier_url: %q\n", ans.FrontierURL)
	fmt.Fprintf(&b, "frontier_model: %q\n", ans.FrontierModel)
	fmt.Fprintf(&b, "frontier_api_key: %q\n", ans.FrontierKey)
	b.WriteString("\n")

	b.WriteString("# --- Inbound auth ---------------------------------------------------------\n")
	fmt.Fprintf(&b, "proxy_api_key: %q\n", ans.ProxyAPIKey)
	b.WriteString("\n")

	b.WriteString("# --- Routing profile ------------------------------------------------------\n")
	fmt.Fprintf(&b, "# profile: %s\n", ans.Profile)
	for envKey, val := range profileKnobs(ans.Profile) {
		if yamlKey, ok := profileYAMLKeys[envKey]; ok {
			fmt.Fprintf(&b, "%s: %s\n", yamlKey, val)
		}
	}
	b.WriteString("\n")

	return os.WriteFile(path, []byte(b.String()), 0o644)
}
