# typed: false
# frozen_string_literal: true
#
# nexus — Hardware-aware AI routing gateway.
#
# ════════════════════════════════════════════════════════════════════
# AUTO-GENERATED BY GORELEASER — DO NOT EDIT BY HAND (issue #1179)
# ════════════════════════════════════════════════════════════════════
#
# The canonical formula lives in the anchapin/homebrew-nexus tap
# repository and is regenerated by GoReleaser on every tagged release
# with the correct url + sha256 from the release assets.
#
# This in-repo copy is a **reference template** so contributors can
# review the formula structure without cloning the tap. It mirrors the
# GoReleaser `brews:` stanza in `.goreleaser.yml`.
#
# Install (end users):
#   brew install anchapin/nexus/nexus

class Nexus < Formula
  desc "Hardware-aware AI routing gateway"
  homepage "https://github.com/anchapin/nexus-proxy"
  # url and sha256 are filled by GoReleaser from release assets.
  # The values below are placeholders for the reference template only.
  url "https://github.com/anchapin/nexus-proxy/releases/download/v0.0.0/nexus_v0.0.0_Darwin_arm64.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  version "0.0.0"
  license "MIT"

  # nexus is a single static binary (CGO-free) — no build deps needed.
  on_macos do
    on_arm do
      # arm64 binary (Apple Silicon)
    end
    on_intel do
      # x86_64 binary (Intel)
    end
  end

  def install
    bin.install "nexus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nexus --version")
  end

  def caveats
    <<~EOS
      nexus is now installed! To start the proxy:

        nexus

      Or run the boot-time diagnostic suite:

        nexus check

      Documentation: https://github.com/anchapin/nexus-proxy#readme
    EOS
  end
end
